export const text = [
  'Perionica Vasic',
  'Cistoca je pola zdravlja!',
  'O nama',
  '1Perionica 1Vasić je vaš pouzdan partner za profesionalno čišćenje 2tepiha, 2automobila, 2kamiona i dubinsko pranje 2nameštaja. Sa našim iskusnim timom i vrhunskom opremom, garantujemo 3vrhunsku 3uslugu i 3besprekorne 3rezultate.',
  'Perionica Vasic',
  'Zdravlje u sjaju automobila.',
  'Pranje automobila',
  'Kada je u pitanju automobil, nudimo sveobuhvatno pranje 2eksterijera i 2enterijera. Naša usluga obuhvata ručno 3pranje, 3poliranje, 3voskiranje, 3pranje 3motora i temeljito čišćenje svake površine unutar vozila. Vaš automobil će izgledati kao nov, sa besprekornim sjajem i svežinom.',
  'Perionica Vasic',
  'Osvežite svoj nameštaj blistavom čistoćom.',
  'Pranje namestaja',
  '1Perionica 1Vasić takođe se specijalizuje za 2dubinsko 2pranje 2nameštaja. Bez obzira da li je u pitanju 3kauč, 3stolica, 3madrac ili 3tepih, naša profesionalna ekipa koristi posebne tehnike i sredstva za uklanjanje nečistoća, alergena i neugodnih mirisa. Vaš nameštaj će biti očišćen do najsitnijih detalja i povratiti svoju prvobitnu svežinu.',
  'Perionica Vasic',
  'Sjaj vašeg kamiona obnovljen kroz profesionalno pranje.',
  'Pranje kamiona',
  'Kamioni često prolaze kroz razne terene i izloženi su teškim uslovima, što rezultira nakupljanjem blata, prašine, ulja i drugih nečistoća. Naša temeljita procedura pranja kamiona obuhvata pažljivo uklanjanje 2svih 2nečistoća kako sa spoljašnjih površina, tako i iz kabine.',
  'Perionica Vasic',
  'Obezbedite čistu svežinu svojim tepisima.',
  'Pranje tepiha',
  '1Koristimo 1visokokvalitetne, 1ekološki prihvatljive proizvode koji su nežni prema vlaknima tepiha, ali istovremeno efikasno uklanjaju mrlje, prašinu, nečistoće i bakterije. Naša temeljita procedura čišćenja obuhvata 3dubinsko 3pranje, 3ispiranje i 3sušenje tepiha, kako bi rezultat bio svež, čist i bez neželjenih mirisa.'
]